<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>

    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Iot.Device.Bindings" Version="4.2.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260318" />
    <PackageReference Include="System.IO.Ports" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Projectreference Include="..\PluginBase\PluginBase.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </Projectreference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\DoksanNPU.png" />
    <EmbeddedResource Include="Resources\IRLogo.png" />
    <EmbeddedResource Include="Resources\IRSensor.png" />
    <EmbeddedResource Include="Resources\PCB.png" />
    <EmbeddedResource Include="Resources\User.png" />
  </ItemGroup>

</Project>
