<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260318" />
  </ItemGroup>

</Project>
